extern int *floor_tiles_list;
extern int *wall_tiles_list;
extern int *machinery_tiles_list;
extern int *furniture_tiles_list;
extern int *container_tiles_list;
extern int *plant_tiles_list;
extern int *misc_tiles_list;
extern int *waypoint_list;
extern int *sidewalk_floor_list;
extern int *water_floor_list;
extern int *grass_floor_list;
extern int *square_floor_list;
extern int *other_floor_list;
extern int *melee_items_list;
extern int *gun_items_list;
extern int *defense_items_list;
extern int *spell_items_list;
extern int *other_items_list;
extern int *all_items_list;

void build_leveleditor_tile_lists(void);
void lvledit_set_obstacle_list_for_category(const char *category_name, struct dynarray *obstacle_list);
